const tg=window.Telegram?.WebApp; if(tg){tg.ready();tg.expand();}
const params=new URLSearchParams(location.search); const startParam=tg?.initDataUnsafe?.start_param||''; const code=params.get('code')||params.get('startapp')||startParam.replace(/^exp_/,''); const app=document.getElementById('app');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function load(){if(!code){app.innerHTML='<section class="screen"><span class="eyebrow">✦ GENZ EXPRESSION</span><h1>Nothing here.</h1><p>Open an Expression link from Telegram.</p></section>';return;} try{const r=await fetch('/api/experience/'+encodeURIComponent(code));if(!r.ok)throw 0;const e=await r.json();render(e);}catch(e){app.innerHTML='<section class="screen"><span class="eyebrow">⚠️</span><h1>Something went wrong.</h1><p>This Expression could not be opened.</p></section>';}}
function render(e){const isQuiz=e.quiz?.length>0; const media=(e.media||[]).length?`<div class="gallery">${e.media.map((_,i)=>`<img src="/media/${esc(e.code)}?idx=${i}" alt="" loading="lazy">`).join('')}</div>`:''; app.innerHTML=`<section id="hero" class="screen"><span class="eyebrow">✦ for you</span><h1>${esc(e.title)}</h1><p>${esc(e.intro)}</p><button onclick="openExp()">Open</button></section><section id="content" class="hidden"><div class="screen"><span class="eyebrow">a little something</span><div class="message">${esc(e.body)}</div></div>${media}${e.audio?`<div class="card"><span class="eyebrow">sound</span><audio controls preload="metadata" src="/audio/${esc(e.code)}"></audio></div>`:''}${isQuiz?quiz(e.quiz):''}<section class="screen"><p>that's it.<br>hope you felt what I meant.</p><button class="secondary" onclick="location.reload()">Replay</button></section></section>`;}
function openExp(){document.getElementById('hero').classList.add('hidden');document.getElementById('content').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});}
function quiz(qs){return `<section class="card" id="quiz"><span class="eyebrow">interactive</span><h2>🎮 Quiz</h2><p>Answer honestly. Your result can appear on the leaderboard.</p>${qs.map((q,i)=>`<div class="card"><b>${i+1}. ${esc(q.question)}</b><input data-q="${i}" placeholder="Your answer" style="margin-top:12px;width:100%;padding:14px;border-radius:14px;border:1px solid #ffffff18;background:#0b0b0b;color:#fff"></div>`).join('')}<button onclick="submitQuiz(${qs.length})">Submit & see ranking</button><div id="result"></div><div id="board" class="leaderboard"></div></section>`}
async function submitQuiz(n){const answers=[...document.querySelectorAll('[data-q]')].sort((a,b)=>+a.dataset.q-+b.dataset.q).map(x=>x.value);const init_data=tg?.initData||'';const result=document.getElementById('result');result.innerHTML='<p>Checking...</p>';try{const r=await fetch('/api/quiz/'+encodeURIComponent(code)+'/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({init_data,answers})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Failed');result.innerHTML=`<div class="card"><h2>🏆 ${d.score}/${d.total}</h2><p>You are currently #${d.rank}.</p></div>`;loadBoard();}catch(e){result.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function loadBoard(){const r=await fetch('/api/quiz/'+encodeURIComponent(code)+'/leaderboard');const d=await r.json();document.getElementById('board').innerHTML='<h3>🏆 Leaderboard</h3>'+(d.items||[]).map((x,i)=>`<div class="rank"><span>${i+1}. ${esc(x.name)}</span><b>${x.score}/${x.total}</b></div>`).join('')||'<p class="muted">Belum ada peserta.</p>';}
load();
